version: "3.2"
services:
  db:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=pass
    volumes:
      - ./mysql-data:/var/lib/mysql