version: "3.3"
services:
  db:
    image: mysql:latest
    restart: always
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=pass
    volumes:
      - my-db:/var/lib/mysql

  mongo2:
    image: mongo:latest
    command: mongod --port 27077
    container_name: mongoCentralGateway
    ports:
      - '27077:27077'
    volumes:
      - mongodb_data:/var/mongo/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoCentralGateway
      - MONGO_INITDB_ROOT_PASSWORD=qqq123wer

volumes:
  my-db:
  mongodb_data: