server:
  port: 9991
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  data:
    mongodb:
      username: mongoCentralGateway
      password: qqq123wer
      port: 27077
      database: CENTRAL_GATEWAY
      authentication-database: admin
      host: localhost